system: lti_system

n_steps: 100

initial_state_mean: [0, 0, 0, 0, 0]
initial_state_cov: [[0.1, 0, 0, 0, 0],
                    [0, 0.1, 0, 0, 0],
                    [0, 0, 0.1, 0, 0],
                    [0, 0, 0, 0.1, 0],
                    [0, 0, 0, 0, 0.1]]

process_noise_mean: [0, 0, 0, 0, 0]
process_noise_cov: [[0.01, 0, 0, 0, 0],
                    [0, 0.01, 0, 0, 0],
                    [0, 0, 0.01, 0, 0],
                    [0, 0, 0, 0.01, 0],
                    [0, 0, 0, 0, 0.01]]

measurement_noise_mean: [0, 0, 0]
measurement_noise_cov: [[0.1, 0, 0],
                         [0, 0.1, 0],
                         [0, 0, 0.1]]

A: [[0.6, 0, 0, 1, 0],
    [0, 0.6, 0, 0, 1],
    [0, 0, 0.7, 0, 0],
    [0, 0, 0, 0.7, 0],
    [0, 0, 0, 0, 0.7]]

B: [[0, 0],
    [0, 0],
    [0, 0],
    [1, 0],
    [0, 1]]

C: [[1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0]]


umin: -0.5
umax: 0.5
input_enabled: false
randomized_matrices: false

state_dimension: 5
input_dimension: 2
output_dimension: 3
matrix_dist: gaussian

